apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-docs
  namespace: personalcook
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: recipe-service
                port:
                  number: 8000
          - path: /openapi.json
            pathType: Prefix
            backend:
              service:
                name: recipe-service
                port:
                  number: 8000
          - path: /redoc
            pathType: Prefix
            backend:
              service:
                name: recipe-service
                port:
                  number: 8000